import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { IKImage } from 'imagekitio-react';
import ImageKit from "imagekit";

const inter = Inter({ subsets: ['latin'] })
const imageFolder = "beaches"

const getImages = () => {
  return new Promise((resolve, reject) => {
    
    // API initialization
    const imgkit = new ImageKit({
      publicKey : process.env.IMAGEKIT_PUBLIC_KEY,
      privateKey : process.env.IMAGEKIT_PRIVATE_KEY,
      urlEndpoint : process.env.IMAGEKIT_ENDPOINT
    })

    // Search for Images in a "specific" Folder
    console.log("fetching images.... ")
    
    imgkit.listFiles({
      path : imageFolder,
      limit: 9
    }, function(error, result){
      if(error) {
        console.error(error)
        reject(error)
      } else {
        // console.log(result)
        resolve(result)
      }
    })  
  })
}

export const getStaticProps = async (context) => {
  
  console.log("Getting images...")
  const images = await getImages()

  return {
    props: {
      images: images.map(image => ({
        url: image.url,
        thumbnail: image.thumbnail
      }))
    }
  }
}

const ImageGalleryMasonry = ({images}) => {
  return (
    <div className='columns-1 md:columns-3 gap-8'>
      {
        images.map((image, index) => {
          const aspectRatio = index % 2 == 0 ? ' aspect-[4/2]' : ' aspect-[3/4]'
          return (
              <img 
                src={image.url}
                className={'mb-8 w-full rounded-lg object-cover trasnition ease-in-out delay-150 hover:scale-150 duration-300' + aspectRatio}
              />
          )
        })
      }
    </div>
  )
}

export default function Home(images) {  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ImageGalleryMasonry {...images} />
      </main>
    </>
  )
}
